# Generated by Django 5.1.15 on 2026-01-21 04:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên danh mục")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Name (English)"
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[("income", "Thu"), ("expense", "Chi")],
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="category", max_length=50, verbose_name="Icon"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#808080", max_length=7, verbose_name="Màu"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Danh mục tài chính",
                "verbose_name_plural": "Danh mục tài chính",
                "ordering": ["category_type", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MinibarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên sản phẩm")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Giá vốn",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Danh mục"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sản phẩm minibar",
                "verbose_name_plural": "Sản phẩm minibar",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Số phòng"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tên phòng"
                    ),
                ),
                ("floor", models.PositiveIntegerField(default=1, verbose_name="Tầng")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Trống"),
                            ("occupied", "Có khách"),
                            ("cleaning", "Đang dọn"),
                            ("maintenance", "Bảo trì"),
                            ("blocked", "Khóa"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tiện nghi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Phòng",
                "verbose_name_plural": "Phòng",
                "ordering": ["floor", "number"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Tên loại phòng"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Name (English)"
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Giá cơ bản",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Số khách tối đa"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "amenities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tiện nghi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loại phòng",
                "verbose_name_plural": "Loại phòng",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Ngày nhận phòng")),
                ("check_out_date", models.DateField(verbose_name="Ngày trả phòng")),
                (
                    "actual_check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Giờ nhận thực tế"
                    ),
                ),
                (
                    "actual_check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Giờ trả thực tế"
                    ),
                ),
                (
                    "guest_count",
                    models.PositiveIntegerField(default=1, verbose_name="Số khách"),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tên khách (deprecated)",
                    ),
                ),
                (
                    "guest_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Số điện thoại (deprecated)",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email (deprecated)"
                    ),
                ),
                (
                    "guest_id_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Số CCCD/Passport (deprecated)",
                    ),
                ),
                (
                    "guest_nationality",
                    models.CharField(
                        blank=True,
                        default="Vietnam",
                        max_length=50,
                        verbose_name="Quốc tịch (deprecated)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("checked_in", "Đang ở"),
                            ("checked_out", "Đã trả phòng"),
                            ("cancelled", "Đã hủy"),
                            ("no_show", "Không đến"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Khách vãng lai"),
                            ("phone", "Điện thoại"),
                            ("website", "Website"),
                            ("booking_com", "Booking.com"),
                            ("agoda", "Agoda"),
                            ("airbnb", "Airbnb"),
                            ("traveloka", "Traveloka"),
                            ("other_ota", "OTA khác"),
                            ("other", "Khác"),
                        ],
                        default="walk_in",
                        max_length=20,
                        verbose_name="Nguồn đặt",
                    ),
                ),
                (
                    "ota_reference",
                    models.CharField(blank=True, max_length=50, verbose_name="Mã OTA"),
                ),
                (
                    "nightly_rate",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Giá/đêm",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="VND", max_length=3, verbose_name="Tiền tệ"
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Tiền cọc",
                    ),
                ),
                (
                    "deposit_paid",
                    models.BooleanField(default=False, verbose_name="Đã đặt cọc"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank_transfer", "Chuyển khoản"),
                            ("momo", "MoMo"),
                            ("vnpay", "VNPay"),
                            ("card", "Thẻ"),
                            ("ota_collect", "OTA thu hộ"),
                            ("other", "Khác"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Hình thức thanh toán",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Đã thanh toán đủ"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Yêu cầu đặc biệt"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đặt phòng",
                "verbose_name_plural": "Đặt phòng",
                "ordering": ["-check_in_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=3, verbose_name="Từ")),
                (
                    "to_currency",
                    models.CharField(default="VND", max_length=3, verbose_name="Sang"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Tỷ giá"
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                (
                    "source",
                    models.CharField(
                        default="manual", max_length=20, verbose_name="Nguồn"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tỷ giá",
                "verbose_name_plural": "Tỷ giá",
                "ordering": ["-date", "from_currency"],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("income", "Thu"), ("expense", "Chi")],
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Số tiền",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="VND", max_length=3, verbose_name="Tiền tệ"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=15,
                        verbose_name="Tỷ giá",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank_transfer", "Chuyển khoản"),
                            ("momo", "MoMo"),
                            ("vnpay", "VNPay"),
                            ("card", "Thẻ"),
                            ("ota_collect", "OTA thu hộ"),
                            ("other", "Khác"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Hình thức thanh toán",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Số hóa đơn"
                    ),
                ),
                (
                    "attachment",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        verbose_name="Ảnh hóa đơn",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_entries",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng liên quan",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="hotel_api.financialcategory",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch tài chính",
                "verbose_name_plural": "Giao dịch tài chính",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Họ và tên"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("cccd", "CCCD (Căn cước công dân)"),
                            ("passport", "Hộ chiếu"),
                            ("cmnd", "CMND (Chứng minh nhân dân)"),
                            ("other", "Khác"),
                        ],
                        default="cccd",
                        max_length=20,
                        verbose_name="Loại giấy tờ",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Số CCCD/Passport",
                    ),
                ),
                (
                    "id_issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày cấp"),
                ),
                (
                    "id_issue_place",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nơi cấp"
                    ),
                ),
                (
                    "id_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="guest_ids/",
                        verbose_name="Ảnh CCCD/Passport",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Vietnam", max_length=50, verbose_name="Quốc tịch"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Thành phố"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Quốc gia"
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="Khách VIP"),
                ),
                (
                    "total_stays",
                    models.PositiveIntegerField(default=0, verbose_name="Số lần ở"),
                ),
                (
                    "preferences",
                    models.JSONField(blank=True, default=dict, verbose_name="Sở thích"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Khách hàng",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "id_number"],
                        name="hotel_api_g_phone_d6c5d2_idx",
                    ),
                    models.Index(
                        fields=["full_name"], name="hotel_api_g_full_na_cdbaf8_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="hotel_api.guest",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.CreateModel(
            name="HotelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Chủ khách sạn"),
                            ("manager", "Quản lý"),
                            ("staff", "Nhân viên"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Số điện thoại"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
        ),
        migrations.CreateModel(
            name="MinibarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Số lượng"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Thành tiền"
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                (
                    "is_charged",
                    models.BooleanField(default=False, verbose_name="Đã tính tiền"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minibar_sales",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="hotel_api.minibaritem",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bán minibar",
                "verbose_name_plural": "Bán minibar",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Housekeeping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("checkout_clean", "Dọn phòng trả"),
                            ("stay_clean", "Dọn phòng đang ở"),
                            ("deep_clean", "Tổng vệ sinh"),
                            ("maintenance", "Bảo trì"),
                            ("inspection", "Kiểm tra"),
                        ],
                        max_length=20,
                        verbose_name="Loại công việc",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("in_progress", "Đang thực hiện"),
                            ("completed", "Hoàn thành"),
                            ("verified", "Đã kiểm tra"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Ngày dự kiến")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hoàn thành lúc"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_housekeeping",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Phân công cho",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="housekeeping_tasks",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng liên quan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_housekeeping",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housekeeping_tasks",
                        to="hotel_api.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Công việc dọn phòng",
                "verbose_name_plural": "Công việc dọn phòng",
                "ordering": ["-scheduled_date", "room__number"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="hotel_api.room",
                verbose_name="Phòng",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="hotel_api.roomtype",
                verbose_name="Loại phòng",
            ),
        ),
    ]
