# Generated by Django 5.1.15 on 2026-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Chủ khách sạn"),
                    ("manager", "Quản lý"),
                    ("staff", "Nhân viên"),
                    ("housekeeping", "Buồng phòng"),
                ],
                default="staff",
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
    ]
