# Generated by Django 5.1.15 on 2026-01-23 02:20

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0002_add_housekeeping_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="additional_charges",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Chi phí phát sinh",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="id_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Số CCCD/Passport",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("cccd", "CCCD (Căn cước công dân)"),
                    ("passport", "Hộ chiếu"),
                    ("cmnd", "CMND (Chứng minh nhân dân)"),
                    ("gplx", "GPLX (Giấy phép lái xe)"),
                    ("other", "Khác"),
                ],
                default="cccd",
                max_length=20,
                verbose_name="Loại giấy tờ",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_date", "check_out_date"], name="hotel_api_b_check_i_124734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status", "room"], name="hotel_api_b_status_682e7d_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["guest", "check_in_date"], name="hotel_api_b_guest_i_789439_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["-created_at"], name="hotel_api_b_created_ee5e15_idx"),
        ),
    ]
