# Generated by Django 5.1.15 on 2026-01-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0003_fix_critical_issues"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Housekeeping",
            new_name="HousekeepingTask",
        ),
    ]
