# Generated by Django 5.1.15 on 2026-01-31 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0004_rename_housekeeping_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NightAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("audit_date", models.DateField(unique=True, verbose_name="Ngày kiểm toán")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("completed", "Hoàn thành"),
                            ("closed", "Đã đóng"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("total_rooms", models.PositiveIntegerField(default=0, verbose_name="Tổng phòng")),
                (
                    "rooms_occupied",
                    models.PositiveIntegerField(default=0, verbose_name="Phòng có khách"),
                ),
                (
                    "rooms_available",
                    models.PositiveIntegerField(default=0, verbose_name="Phòng trống"),
                ),
                (
                    "rooms_cleaning",
                    models.PositiveIntegerField(default=0, verbose_name="Phòng đang dọn"),
                ),
                (
                    "rooms_maintenance",
                    models.PositiveIntegerField(default=0, verbose_name="Phòng bảo trì"),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Tỷ lệ lấp đầy (%)"
                    ),
                ),
                (
                    "check_ins_today",
                    models.PositiveIntegerField(default=0, verbose_name="Check-in hôm nay"),
                ),
                (
                    "check_outs_today",
                    models.PositiveIntegerField(default=0, verbose_name="Check-out hôm nay"),
                ),
                ("no_shows", models.PositiveIntegerField(default=0, verbose_name="Không đến")),
                (
                    "cancellations",
                    models.PositiveIntegerField(default=0, verbose_name="Hủy đặt phòng"),
                ),
                (
                    "new_bookings",
                    models.PositiveIntegerField(default=0, verbose_name="Đặt phòng mới"),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Tổng thu"
                    ),
                ),
                (
                    "room_revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Doanh thu phòng"
                    ),
                ),
                (
                    "other_revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Doanh thu khác"
                    ),
                ),
                (
                    "total_expense",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Tổng chi"
                    ),
                ),
                (
                    "net_revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Lợi nhuận ròng"
                    ),
                ),
                (
                    "cash_collected",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Tiền mặt thu"
                    ),
                ),
                (
                    "bank_transfer_collected",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Chuyển khoản thu"
                    ),
                ),
                (
                    "momo_collected",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="MoMo thu"
                    ),
                ),
                (
                    "other_payments",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Thanh toán khác"
                    ),
                ),
                (
                    "pending_payments",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=15, verbose_name="Thanh toán chờ"
                    ),
                ),
                (
                    "unpaid_bookings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số đặt phòng chưa thanh toán"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "performed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Thực hiện lúc"),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Đóng lúc")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đóng",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="night_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiểm toán cuối ngày",
                "verbose_name_plural": "Kiểm toán cuối ngày",
                "ordering": ["-audit_date"],
                "indexes": [
                    models.Index(fields=["-audit_date"], name="hotel_api_n_audit_d_b920ef_idx"),
                    models.Index(
                        fields=["status", "-audit_date"], name="hotel_api_n_status_ffad56_idx"
                    ),
                ],
            },
        ),
    ]
