# Generated by Django 5.1.15 on 2026-01-31 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0005_night_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("room", "Tiền phòng"),
                            ("minibar", "Minibar"),
                            ("laundry", "Giặt ủi"),
                            ("food", "Thức ăn/Đồ uống"),
                            ("service", "Dịch vụ khác"),
                            ("extra_bed", "Giường phụ"),
                            ("early_checkin", "Check-in sớm"),
                            ("late_checkout", "Check-out muộn"),
                            ("damage", "Hư hỏng"),
                            ("other", "Khác"),
                        ],
                        default="service",
                        max_length=20,
                        verbose_name="Loại",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="Mô tả")),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Số lượng")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Đơn giá",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Thành tiền",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Đã thanh toán")),
                ("is_voided", models.BooleanField(default=False, verbose_name="Đã hủy")),
                ("void_reason", models.TextField(blank=True, verbose_name="Lý do hủy")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folio_items",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folio_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "minibar_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="folio_item",
                        to="hotel_api.minibarsale",
                        verbose_name="Bán minibar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi phí phát sinh",
                "verbose_name_plural": "Chi phí phát sinh",
                "ordering": ["booking", "date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Đặt cọc"),
                            ("room_charge", "Tiền phòng"),
                            ("extra_charge", "Phụ thu"),
                            ("refund", "Hoàn tiền"),
                            ("adjustment", "Điều chỉnh"),
                        ],
                        default="room_charge",
                        max_length=20,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Số tiền",
                    ),
                ),
                ("currency", models.CharField(default="VND", max_length=3, verbose_name="Tiền tệ")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("bank_transfer", "Chuyển khoản"),
                            ("momo", "MoMo"),
                            ("vnpay", "VNPay"),
                            ("card", "Thẻ"),
                            ("ota_collect", "OTA thu hộ"),
                            ("other", "Khác"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Hình thức thanh toán",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                            ("refunded", "Đã hoàn"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Mã giao dịch"),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="Số tham chiếu"),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Số hóa đơn"),
                ),
                (
                    "receipt_generated",
                    models.BooleanField(default=False, verbose_name="Đã tạo hóa đơn"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "payment_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày thanh toán"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thanh toán",
                "verbose_name_plural": "Thanh toán",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "-payment_date"], name="hotel_api_p_booking_4fb7b2_idx"
                    ),
                    models.Index(
                        fields=["status", "-payment_date"], name="hotel_api_p_status_913b53_idx"
                    ),
                    models.Index(
                        fields=["payment_type", "-payment_date"],
                        name="hotel_api_p_payment_4f24b2_idx",
                    ),
                ],
            },
        ),
    ]
