# Generated by Django 5.1.15 on 2026-02-01 22:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0006_add_payment_folio_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        help_text="Mô tả vị trí nếu không phải phòng (ví dụ: Sảnh, Hành lang tầng 2)",
                        max_length=200,
                        verbose_name="Vị trí cụ thể",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("description", models.TextField(verbose_name="Mô tả chi tiết")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electrical", "Điện"),
                            ("plumbing", "Nước"),
                            ("ac_heating", "Điều hòa/Sưởi"),
                            ("furniture", "Nội thất"),
                            ("appliance", "Thiết bị"),
                            ("structural", "Kết cấu"),
                            ("safety", "An toàn"),
                            ("other", "Khác"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("urgent", "Khẩn cấp"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Mức ưu tiên",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xử lý"),
                            ("assigned", "Đã phân công"),
                            ("in_progress", "Đang thực hiện"),
                            ("on_hold", "Tạm dừng"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Phân công lúc"),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Chi phí dự kiến",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Chi phí thực tế",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Ghi chú hoàn thành"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Hoàn thành lúc"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Phân công cho",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_maintenance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người hoàn thành",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người báo cáo",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Để trống nếu là khu vực công cộng",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="hotel_api.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu bảo trì",
                "verbose_name_plural": "Yêu cầu bảo trì",
                "ordering": ["-created_at"],
            },
        ),
    ]
