# Generated by Django 5.1.15 on 2026-02-04 01:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0007_add_maintenance_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[("overnight", "Qua đêm"), ("hourly", "Theo giờ")],
                default="overnight",
                max_length=20,
                verbose_name="Loại đặt phòng",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="early_check_in_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Phí nhận sớm",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="early_check_in_hours",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=4, verbose_name="Số giờ nhận sớm"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="expected_check_out_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Thời điểm trả phòng dự kiến cho đặt theo giờ",
                null=True,
                verbose_name="Giờ trả dự kiến",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Giá/giờ",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hours_booked",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Chỉ áp dụng cho đặt phòng theo giờ",
                null=True,
                verbose_name="Số giờ đặt",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="late_check_out_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Phí trả muộn",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="late_check_out_hours",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=4, verbose_name="Số giờ trả muộn"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="allows_hourly",
            field=models.BooleanField(default=True, verbose_name="Cho phép đặt theo giờ"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="first_hour_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Giá cho 2-3 giờ đầu tiên (thường cao hơn)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Giá giờ đầu tiên",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Giá theo giờ",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="min_hours",
            field=models.PositiveIntegerField(default=2, verbose_name="Số giờ tối thiểu"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="base_rate",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Giá cơ bản/đêm",
            ),
        ),
        migrations.CreateModel(
            name="GroupBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên đoàn/nhóm")),
                ("contact_name", models.CharField(max_length=100, verbose_name="Người liên hệ")),
                ("contact_phone", models.CharField(max_length=20, verbose_name="SĐT liên hệ")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=200, verbose_name="Công ty/Tổ chức"),
                ),
                ("check_in_date", models.DateField(verbose_name="Ngày nhận phòng")),
                ("check_out_date", models.DateField(verbose_name="Ngày trả phòng")),
                (
                    "actual_check_in",
                    models.DateTimeField(blank=True, null=True, verbose_name="Giờ nhận thực tế"),
                ),
                (
                    "actual_check_out",
                    models.DateTimeField(blank=True, null=True, verbose_name="Giờ trả thực tế"),
                ),
                ("room_count", models.PositiveIntegerField(verbose_name="Số phòng")),
                ("guest_count", models.PositiveIntegerField(verbose_name="Số khách")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tiền cọc",
                    ),
                ),
                ("deposit_paid", models.BooleanField(default=False, verbose_name="Đã đặt cọc")),
                (
                    "special_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Giá đặc biệt/đêm",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Giảm giá (%)"
                    ),
                ),
                ("currency", models.CharField(default="VND", max_length=3, verbose_name="Tiền tệ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tentative", "Đang chờ"),
                            ("confirmed", "Đã xác nhận"),
                            ("checked_in", "Đang ở"),
                            ("checked_out", "Đã trả phòng"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="tentative",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Khách vãng lai"),
                            ("phone", "Điện thoại"),
                            ("website", "Website"),
                            ("booking_com", "Booking.com"),
                            ("agoda", "Agoda"),
                            ("airbnb", "Airbnb"),
                            ("traveloka", "Traveloka"),
                            ("other_ota", "OTA khác"),
                            ("other", "Khác"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="Nguồn đặt",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("special_requests", models.TextField(blank=True, verbose_name="Yêu cầu đặc biệt")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_group_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_bookings",
                        to="hotel_api.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đặt phòng nhóm",
                "verbose_name_plural": "Đặt phòng nhóm",
                "ordering": ["-check_in_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LostAndFound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item_name", models.CharField(max_length=200, verbose_name="Tên vật phẩm")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả chi tiết")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Đồ điện tử"),
                            ("clothing", "Quần áo"),
                            ("jewelry", "Trang sức"),
                            ("documents", "Giấy tờ"),
                            ("money", "Tiền"),
                            ("bags", "Túi/Vali"),
                            ("personal", "Đồ cá nhân"),
                            ("other", "Khác"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Giá trị ước tính",
                    ),
                ),
                (
                    "found_location",
                    models.CharField(
                        blank=True,
                        help_text="Vị trí cụ thể nếu không phải phòng",
                        max_length=200,
                        verbose_name="Nơi tìm thấy",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=200, verbose_name="Nơi lưu giữ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("found", "Đã tìm thấy"),
                            ("stored", "Đang lưu giữ"),
                            ("claimed", "Đã trả khách"),
                            ("donated", "Đã quyên góp"),
                            ("disposed", "Đã tiêu hủy"),
                        ],
                        default="found",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("found_date", models.DateField(verbose_name="Ngày tìm thấy")),
                (
                    "claimed_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày trả khách"),
                ),
                (
                    "disposed_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày tiêu hủy/quyên góp"),
                ),
                (
                    "guest_contacted",
                    models.BooleanField(default=False, verbose_name="Đã liên hệ khách"),
                ),
                ("contact_notes", models.TextField(blank=True, verbose_name="Ghi chú liên hệ")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="lost_found/", verbose_name="Ảnh vật phẩm"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost_items",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "claimed_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nhân viên trả",
                    ),
                ),
                (
                    "found_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="found_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tìm thấy",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost_items",
                        to="hotel_api.guest",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lost_items",
                        to="hotel_api.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vật thất lạc",
                "verbose_name_plural": "Vật thất lạc",
                "ordering": ["-found_date", "-created_at"],
            },
        ),
    ]
