# Generated by Django 5.1.15 on 2026-02-05 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0008_add_phase3_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên mẫu")),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("checkout", "Sau khi trả phòng"),
                            ("checkin", "Trước khi nhận phòng"),
                            ("routine", "Kiểm tra định kỳ"),
                            ("maintenance", "Kiểm tra bảo trì"),
                            ("deep_clean", "Kiểm tra vệ sinh tổng"),
                        ],
                        default="checkout",
                        max_length=20,
                        verbose_name="Loại kiểm tra",
                    ),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="Mẫu mặc định")),
                ("is_active", models.BooleanField(default=True, verbose_name="Còn sử dụng")),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="Danh sách các mục cần kiểm tra",
                        verbose_name="Các mục kiểm tra",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_templates",
                        to="hotel_api.roomtype",
                        verbose_name="Loại phòng áp dụng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mẫu kiểm tra",
                "verbose_name_plural": "Mẫu kiểm tra",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("checkout", "Sau khi trả phòng"),
                            ("checkin", "Trước khi nhận phòng"),
                            ("routine", "Kiểm tra định kỳ"),
                            ("maintenance", "Kiểm tra bảo trì"),
                            ("deep_clean", "Kiểm tra vệ sinh tổng"),
                        ],
                        default="checkout",
                        max_length=20,
                        verbose_name="Loại kiểm tra",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="Ngày kiểm tra")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm hoàn thành"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ kiểm tra"),
                            ("in_progress", "Đang kiểm tra"),
                            ("completed", "Hoàn thành"),
                            ("requires_action", "Cần xử lý"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách các mục kiểm tra và kết quả",
                        verbose_name="Danh sách kiểm tra",
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0, verbose_name="Tổng số mục")),
                ("passed_items", models.PositiveIntegerField(default=0, verbose_name="Số mục đạt")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Điểm (%)"
                    ),
                ),
                (
                    "issues_found",
                    models.PositiveIntegerField(default=0, verbose_name="Số vấn đề phát hiện"),
                ),
                (
                    "critical_issues",
                    models.PositiveIntegerField(default=0, verbose_name="Vấn đề nghiêm trọng"),
                ),
                ("images", models.JSONField(blank=True, default=list, verbose_name="Ảnh kiểm tra")),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú tổng thể")),
                (
                    "action_required",
                    models.TextField(blank=True, verbose_name="Hành động cần thực hiện"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng liên quan",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người kiểm tra",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="hotel_api.room",
                        verbose_name="Phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiểm tra phòng",
                "verbose_name_plural": "Kiểm tra phòng",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
    ]
