# Generated by Django 5.1.15 on 2026-02-05 22:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0009_add_room_inspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="declaration_submitted",
            field=models.BooleanField(default=False, verbose_name="Đã khai báo tạm trú"),
        ),
        migrations.AddField(
            model_name="booking",
            name="declaration_submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Thời gian khai báo"),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Giảm giá",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="discount_reason",
            field=models.CharField(blank=True, max_length=100, verbose_name="Lý do giảm giá"),
        ),
        migrations.AddField(
            model_name="booking",
            name="internal_notes",
            field=models.TextField(
                blank=True, help_text="Ghi chú chỉ nhân viên thấy", verbose_name="Ghi chú nội bộ"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="ota_commission",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Hoa hồng OTA",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="first_stay",
            field=models.DateField(blank=True, null=True, verbose_name="Lần đầu ở"),
        ),
        migrations.AddField(
            model_name="guest",
            name="last_stay",
            field=models.DateField(blank=True, null=True, verbose_name="Lần cuối ở"),
        ),
        migrations.AddField(
            model_name="guest",
            name="preferred_floor",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Tầng ưa thích"),
        ),
        migrations.AddField(
            model_name="guest",
            name="preferred_room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_guests",
                to="hotel_api.roomtype",
                verbose_name="Loại phòng ưa thích",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="special_requests",
            field=models.TextField(blank=True, verbose_name="Yêu cầu đặc biệt"),
        ),
        migrations.AddField(
            model_name="guest",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=15, verbose_name="Tổng chi tiêu"
            ),
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="can_edit_rates",
            field=models.BooleanField(default=False, verbose_name="Sửa giá phòng"),
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="can_manage_bookings",
            field=models.BooleanField(default=True, verbose_name="Quản lý đặt phòng"),
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="can_view_finance",
            field=models.BooleanField(default=False, verbose_name="Xem tài chính"),
        ),
        migrations.AddField(
            model_name="hoteluser",
            name="receive_notifications",
            field=models.BooleanField(default=True, verbose_name="Nhận thông báo"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("bank_transfer", "Chuyển khoản"),
                    ("momo", "MoMo"),
                    ("vnpay", "VNPay"),
                    ("zalopay", "ZaloPay"),
                    ("card", "Thẻ"),
                    ("ota_collect", "OTA thu hộ"),
                    ("other", "Khác"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("walk_in", "Khách vãng lai"),
                    ("phone", "Điện thoại"),
                    ("website", "Website"),
                    ("booking_com", "Booking.com"),
                    ("agoda", "Agoda"),
                    ("airbnb", "Airbnb"),
                    ("expedia", "Expedia"),
                    ("traveloka", "Traveloka"),
                    ("google_hotel", "Google Hotel"),
                    ("other_ota", "OTA khác"),
                    ("other", "Khác"),
                ],
                default="walk_in",
                max_length=20,
                verbose_name="Nguồn đặt",
            ),
        ),
        migrations.AlterField(
            model_name="financialentry",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("bank_transfer", "Chuyển khoản"),
                    ("momo", "MoMo"),
                    ("vnpay", "VNPay"),
                    ("zalopay", "ZaloPay"),
                    ("card", "Thẻ"),
                    ("ota_collect", "OTA thu hộ"),
                    ("other", "Khác"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="groupbooking",
            name="source",
            field=models.CharField(
                choices=[
                    ("walk_in", "Khách vãng lai"),
                    ("phone", "Điện thoại"),
                    ("website", "Website"),
                    ("booking_com", "Booking.com"),
                    ("agoda", "Agoda"),
                    ("airbnb", "Airbnb"),
                    ("expedia", "Expedia"),
                    ("traveloka", "Traveloka"),
                    ("google_hotel", "Google Hotel"),
                    ("other_ota", "OTA khác"),
                    ("other", "Khác"),
                ],
                default="phone",
                max_length=20,
                verbose_name="Nguồn đặt",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("bank_transfer", "Chuyển khoản"),
                    ("momo", "MoMo"),
                    ("vnpay", "VNPay"),
                    ("zalopay", "ZaloPay"),
                    ("card", "Thẻ"),
                    ("ota_collect", "OTA thu hộ"),
                    ("other", "Khác"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
    ]
