# Generated by Django 5.1.15 on 2026-02-06 01:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0010_design_gaps_fixes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateRateOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Giá",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="VD: Tết, Lễ hội, Cuối tuần",
                        max_length=100,
                        verbose_name="Lý do",
                    ),
                ),
                (
                    "closed_to_arrival",
                    models.BooleanField(
                        default=False,
                        help_text="Không cho phép check-in ngày này",
                        verbose_name="Đóng nhận khách",
                    ),
                ),
                (
                    "closed_to_departure",
                    models.BooleanField(
                        default=False,
                        help_text="Không cho phép check-out ngày này",
                        verbose_name="Đóng trả phòng",
                    ),
                ),
                (
                    "min_stay",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Yêu cầu số đêm tối thiểu cho ngày này",
                        null=True,
                        verbose_name="Số đêm tối thiểu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_overrides",
                        to="hotel_api.roomtype",
                        verbose_name="Loại phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Điều chỉnh giá theo ngày",
                "verbose_name_plural": "Điều chỉnh giá theo ngày",
                "ordering": ["room_type", "date"],
                "unique_together": {("room_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên gói giá")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=50, verbose_name="Name (English)"),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Giá cơ bản/đêm",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                (
                    "min_stay",
                    models.PositiveIntegerField(default=1, verbose_name="Số đêm tối thiểu"),
                ),
                (
                    "max_stay",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số đêm tối đa"
                    ),
                ),
                (
                    "advance_booking_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Yêu cầu đặt trước ít nhất X ngày",
                        null=True,
                        verbose_name="Số ngày đặt trước",
                    ),
                ),
                (
                    "cancellation_policy",
                    models.CharField(
                        choices=[
                            ("free", "Miễn phí hủy"),
                            ("flexible", "Linh hoạt"),
                            ("moderate", "Trung bình"),
                            ("strict", "Nghiêm ngặt"),
                            ("non_refundable", "Không hoàn tiền"),
                        ],
                        default="flexible",
                        max_length=20,
                        verbose_name="Chính sách hủy",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="Có hiệu lực từ"),
                ),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="Có hiệu lực đến"),
                ),
                (
                    "blackout_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách ngày không áp dụng gói giá này",
                        verbose_name="Ngày không áp dụng",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Danh sách kênh áp dụng: booking_com, agoda, direct, etc.",
                        verbose_name="Kênh phân phối",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "includes_breakfast",
                    models.BooleanField(default=False, verbose_name="Bao gồm bữa sáng"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_plans",
                        to="hotel_api.roomtype",
                        verbose_name="Loại phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gói giá",
                "verbose_name_plural": "Gói giá",
                "ordering": ["room_type", "name"],
                "unique_together": {("room_type", "name")},
            },
        ),
    ]
