# Generated by Django 5.1.15 on 2026-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0011_add_rateplan_and_daterateoverride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="notes",
            field=models.TextField(blank=True, default="", null=True, verbose_name="Ghi chú"),
        ),
    ]
