# Generated by Django 5.1.15 on 2026-02-09 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0012_allow_null_notes_in_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.TextField(unique=True, verbose_name="FCM Token")),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        default="android",
                        max_length=10,
                        verbose_name="Nền tảng",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Tên thiết bị"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token thiết bị",
                "verbose_name_plural": "Token thiết bị",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="hotel_api_d_user_id_49f836_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_created", "Đặt phòng mới"),
                            ("booking_confirmed", "Xác nhận đặt phòng"),
                            ("booking_cancelled", "Hủy đặt phòng"),
                            ("checkin_reminder", "Nhắc nhận phòng"),
                            ("checkout_reminder", "Nhắc trả phòng"),
                            ("checkin_completed", "Đã nhận phòng"),
                            ("checkout_completed", "Đã trả phòng"),
                            ("general", "Thông báo chung"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="Loại thông báo",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("body", models.TextField(verbose_name="Nội dung")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Dữ liệu bổ sung"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Đọc lúc")),
                ("is_sent", models.BooleanField(default=False, verbose_name="Đã gửi push")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Gửi lúc")),
                ("send_error", models.TextField(blank=True, verbose_name="Lỗi gửi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng liên quan",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"], name="hotel_api_n_recipie_d9b0a9_idx"
                    ),
                    models.Index(
                        fields=["recipient", "is_read"], name="hotel_api_n_recipie_7e1ec6_idx"
                    ),
                ],
            },
        ),
    ]
