# Generated by Django 5.1.15 on 2026-02-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0013_notification_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên mẫu")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Xác nhận đặt phòng"),
                            ("pre_arrival", "Thông tin trước khi đến"),
                            ("checkout_reminder", "Nhắc trả phòng"),
                            ("review_request", "Yêu cầu đánh giá"),
                            ("custom", "Tùy chỉnh"),
                        ],
                        default="custom",
                        max_length=30,
                        verbose_name="Loại mẫu",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Dùng {guest_name}, {room_number}, {check_in_date}, {check_out_date}, {hotel_name} làm biến",
                        max_length=200,
                        verbose_name="Tiêu đề",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Dùng {guest_name}, {room_number}, {check_in_date}, {check_out_date}, {hotel_name}, {total_amount}, {nights} làm biến",
                        verbose_name="Nội dung",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email"), ("zalo", "Zalo")],
                        default="sms",
                        max_length=10,
                        verbose_name="Kênh gửi",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Đang hoạt động")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mẫu tin nhắn",
                "verbose_name_plural": "Mẫu tin nhắn",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="GuestMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email"), ("zalo", "Zalo")],
                        max_length=10,
                        verbose_name="Kênh gửi",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("body", models.TextField(verbose_name="Nội dung")),
                (
                    "recipient_address",
                    models.CharField(
                        blank=True,
                        help_text="Số điện thoại hoặc email",
                        max_length=200,
                        verbose_name="Địa chỉ nhận",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Đang gửi"),
                            ("sent", "Đã gửi"),
                            ("delivered", "Đã nhận"),
                            ("failed", "Thất bại"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Gửi lúc")),
                ("send_error", models.TextField(blank=True, verbose_name="Lỗi gửi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_messages",
                        to="hotel_api.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="hotel_api.guest",
                        verbose_name="Khách",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_guest_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="hotel_api.messagetemplate",
                        verbose_name="Mẫu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn khách",
                "verbose_name_plural": "Tin nhắn khách",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["guest", "-created_at"], name="hotel_api_g_guest_i_71bbeb_idx"
                    ),
                    models.Index(
                        fields=["booking", "-created_at"], name="hotel_api_g_booking_43c1ce_idx"
                    ),
                    models.Index(fields=["status"], name="hotel_api_g_status_fa8768_idx"),
                ],
            },
        ),
    ]
