# Generated by Django 5.1.15 on 2026-02-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0014_guest_messaging_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="entry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày nhập cảnh"),
        ),
        migrations.AddField(
            model_name="guest",
            name="entry_port",
            field=models.CharField(
                blank=True,
                help_text="Ví dụ: Sân bay Tân Sơn Nhất, Sân bay Nội Bài...",
                max_length=100,
                verbose_name="Cửa khẩu nhập cảnh",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="entry_purpose",
            field=models.CharField(
                blank=True,
                help_text="Ví dụ: Du lịch, Công tác, Thăm thân...",
                max_length=200,
                verbose_name="Mục đích nhập cảnh",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="passport_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ordinary", "Phổ thông"),
                    ("official", "Công vụ"),
                    ("diplomatic", "Ngoại giao"),
                    ("other", "Khác"),
                ],
                help_text="Phổ thông, công vụ, ngoại giao...",
                max_length=20,
                verbose_name="Loại hộ chiếu",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Thời hạn thị thực"),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày cấp thị thực"),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_issuing_authority",
            field=models.CharField(blank=True, max_length=200, verbose_name="Cơ quan cấp thị thực"),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Số thị thực/thẻ tạm trú"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("visa", "Thị thực (Visa)"),
                    ("temp_residence_card", "Thẻ tạm trú"),
                    ("visa_exemption", "Giấy miễn thị thực"),
                    ("abtc", "Thẻ ABTC"),
                    ("none", "Miễn thị thực"),
                ],
                help_text="Thị thực, thẻ tạm trú, giấy miễn thị thực, thẻ ABTC",
                max_length=30,
                verbose_name="Loại giấy tờ nhập cảnh",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="nationality",
            field=models.CharField(default="Việt Nam", max_length=50, verbose_name="Quốc tịch"),
        ),
    ]
