# Generated by Django 5.1.15 on 2026-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0015_add_foreign_guest_na17_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialentry",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Mô tả"),
        ),
    ]
