# Generated by Django 5.1.15 on 2026-02-13 23:00

import django.db.models.deletion
import hotel_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0016_make_financial_entry_description_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_id_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_nationality",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_phone",
        ),
        migrations.AddField(
            model_name="booking",
            name="rate_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="hotel_api.rateplan",
                verbose_name="Gói giá",
            ),
        ),
        migrations.AlterField(
            model_name="financialentry",
            name="attachment",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="receipts/",
                validators=[hotel_api.models.validate_image_file],
                verbose_name="Ảnh hóa đơn",
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="id_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="guest_ids/",
                validators=[hotel_api.models.validate_image_file],
                verbose_name="Ảnh CCCD/Passport",
            ),
        ),
        migrations.AlterField(
            model_name="lostandfound",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lost_found/",
                validators=[hotel_api.models.validate_image_file],
                verbose_name="Ảnh vật phẩm",
            ),
        ),
    ]
