# Generated by Django 5.1.15 on 2026-02-16 21:37

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def compute_hashes(apps, schema_editor):
    """Compute SHA-256 hashes for existing id_number and visa_number values."""
    Guest = apps.get_model("hotel_api", "Guest")
    for guest in Guest.objects.all():
        changed = False
        if guest.id_number:
            guest.id_number_hash = hashlib.sha256(
                guest.id_number.strip().encode()
            ).hexdigest()
            changed = True
        if guest.visa_number:
            guest.visa_number_hash = hashlib.sha256(
                guest.visa_number.strip().encode()
            ).hexdigest()
            changed = True
        if changed:
            guest.save(update_fields=["id_number_hash", "visa_number_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0017_remove_deprecated_guest_fields_add_rate_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveDataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view_guest", "Xem thông tin khách"),
                            ("list_guests", "Xem danh sách khách"),
                            ("search_guest", "Tìm kiếm khách"),
                            ("create_guest", "Tạo khách mới"),
                            ("update_guest", "Cập nhật thông tin khách"),
                            ("view_guest_history", "Xem lịch sử khách"),
                            ("export_declaration", "Xuất khai báo tạm trú"),
                            ("export_receipt", "Xuất biên lai"),
                        ],
                        max_length=30,
                        verbose_name="Hành động",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(default="guest", max_length=30, verbose_name="Loại dữ liệu"),
                ),
                (
                    "resource_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID đối tượng"),
                ),
                (
                    "fields_accessed",
                    models.JSONField(default=list, verbose_name="Trường dữ liệu đã truy cập"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="Địa chỉ IP"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=500, verbose_name="User Agent"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Chi tiết bổ sung"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Thời gian")),
            ],
            options={
                "verbose_name": "Nhật ký truy cập dữ liệu nhạy cảm",
                "verbose_name_plural": "Nhật ký truy cập dữ liệu nhạy cảm",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveIndex(
            model_name="guest",
            name="hotel_api_g_phone_d6c5d2_idx",
        ),
        migrations.AddField(
            model_name="guest",
            name="id_number_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Hash CCCD/Passport",
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="visa_number_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="Hash thị thực"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Số CCCD/Passport"
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="visa_number",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Số thị thực/thẻ tạm trú"
            ),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["phone", "id_number_hash"], name="hotel_api_g_phone_89fc91_idx"
            ),
        ),
        migrations.RunPython(compute_hashes, migrations.RunPython.noop),
        migrations.AddField(
            model_name="sensitivedataaccesslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensitive_data_access_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người truy cập",
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccesslog",
            index=models.Index(
                fields=["user", "-timestamp"], name="hotel_api_s_user_id_429d32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccesslog",
            index=models.Index(
                fields=["action", "-timestamp"], name="hotel_api_s_action_ed02f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensitivedataaccesslog",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="hotel_api_s_resourc_e5d1dc_idx"
            ),
        ),
    ]
