# Generated by Django 5.1.15 on 2026-03-04 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0018_guest_encryption_and_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Tên người dùng"),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Hành động")),
                ("entity_type", models.CharField(max_length=50, verbose_name="Loại đối tượng")),
                (
                    "entity_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID đối tượng"),
                ),
                ("details", models.TextField(blank=True, default="", verbose_name="Chi tiết")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="Địa chỉ IP"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Thời gian")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký hoạt động",
                "verbose_name_plural": "Nhật ký hoạt động",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="hotel_api_a_user_id_d109fc_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "-created_at"], name="hotel_api_a_entity__688afe_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="hotel_api_a_entity__88c245_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="hotel_api_a_action_739ea3_idx"
                    ),
                ],
            },
        ),
    ]
