# Generated by Django 5.1.15 on 2026-03-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0019_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Số hóa đơn"
            ),
        ),
    ]
