# Generated by Django 5.1.15 on 2026-03-19 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_api", "0020_unique_receipt_number_and_balance_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="financialcategory",
            unique_together={("name", "category_type")},
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(fields=["date", "entry_type"], name="hotel_api_f_date_159530_idx"),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(fields=["category", "date"], name="hotel_api_f_categor_72defb_idx"),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(fields=["payment_method"], name="hotel_api_f_payment_e4322b_idx"),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["status", "scheduled_date"], name="hotel_api_h_status_40fb95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="hotel_api_h_assigne_02887f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="housekeepingtask",
            index=models.Index(
                fields=["task_type", "scheduled_date"], name="hotel_api_h_task_ty_7e4a32_idx"
            ),
        ),
    ]
